# Generated by Django 2.2.28 on 2024-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_rental', '0008_alter_addrentalhome_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrentalhome',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
